feat(component): add new feature button that returns the user to the beginning of the page.
AnguHashBlog/angular-primeng pull request #57
Opened 2024-03-23 09:30 UTC by DongreJaipal

## This PR Closes Issue  closes #
https://github.com/AnguHashBlog/angular-primeng/issues/28

## Description
long blog posts there should be a scroll to pop button / icon that returns the user to the beginning of the page
for this app version primeicons used
applied in the app.component 

## What type of PR is this? (check all applicable)

- [✓] 🅰️ Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings
[Attach screenshots or recordings if applicable]

## Steps to QA

## Added to documentation?
- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

## [Optional] Post-deployment tasks
[Specify any post-deployment tasks that need to be performed]

## [Optional] What gif best describes this PR or how it makes you feel? 
[Embed gif or describe the feeling in plain text]

2024-03-26 05:45 UTC, monacodelisa requested changes

2024-03-26 05:45 UTC, monacodelisa commented on angular-primeng-app/src/app/app.component.html
> +@if (enableScrollUp) {
@DongreJaipal let's name the condition `showScrollButton`

2024-03-26 05:45 UTC, monacodelisa commented on angular-primeng-app/src/app/app.component.html
> +<p-button class="pageUpButton" (click)="goPageTop()" icon="pi pi-angle-up" [rounded]="true" size="small"></p-button>
@DongreJaipal and then the on click event should be named `scrollToTop()`

2024-03-26 05:45 UTC, monacodelisa commented on angular-primeng-app/src/app/app.component.ts
> +	imports: [RouterOutlet, HeaderComponent, FooterComponent,ButtonModule],
@DongreJaipal could you add a space before `ButtonModule` so there is a space between the comma and the button module like this 
`imports: [RouterOutlet, HeaderComponent, FooterComponent, ButtonModule],`

2024-03-26 05:45 UTC, monacodelisa commented on angular-primeng-app/src/app/app.component.ts
> +	enableScrollUp: boolean=false;
@DongreJaipal for over here, I am not sure that we need this to be a subscription. 
so let's change `private scrollEvntSub?: Subscription;` to be - `showScrollButton: boolean = false;`

2024-03-26 05:45 UTC, monacodelisa commented on angular-primeng-app/src/app/app.component.ts
> +
@DongreJaipal and over here the using the logic you suggested, which looks good, we can use the `HostListener` which needs to be added as an import from '@angular/core' and can be used like this:

```
onWindowScroll() {
    // Check the vertical scroll position
    const yOffset = window.pageYOffset || document.documentElement.scrollTop;
    if (yOffset > 300) { // this value might need adjustments
      this.showScrollButton = true;
    } else {
      this.showScrollButton = false;
    }
  }
```
and then bellow it, the click event function 

```
  scrollToTop() {
    this.viewportScroller.scrollToPosition([0, 0]);
  }
```
please give it a try and let me know if you need any further assistance

2024-03-27 07:42 UTC, monacodelisa approved these changes

2024-03-27 07:42 UTC, esteecodes approved these changes

2024-03-27 07:43 UTC, copypasteov approved these changes

2024-03-27 07:45 UTC, merged

2024-03-27 07:55 UTC, monacodelisa commented
@DongreJaipal thank you for your contribution 🚀