Feature: author and co-authors to be clickable links leading to the author's page on Hashnode
AnguHashBlog/angular-primeng pull request #72
Opened 2024-05-13 23:51 UTC by MestiriBaha

## This PR Closes Issue 
closes #

## Description
I added links in the PostDetails component for the authors and co-authors images that will open in a new tab. However, I encountered an issue with special names, such as {{ MonaCodeLisa }}, where the presence of curly brackets caused incorrect ASCII formatting in the links (e.g., https://example.com/@%7B%7MonaCodeLisa %7D%7D). To resolve this problem and ensure proper URL formatting, I created a custom pipe. This pipe removes curly brackets and extra spaces from names, providing an extensible solution for handling special characters throughout the application
## What type of PR is this? (check all applicable)

- [yes] 🅰️ Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings
[Attach screenshots or recordings if applicable]
Before Adding the custom pipe  : 
![image](https://github.com/AnguHashBlog/angular-primeng/assets/92154267/bf61df47-7076-466e-b4f1-c2dfb217c534)
After I added the custom pipe : 
![image](https://github.com/AnguHashBlog/angular-primeng/assets/92154267/59dd2d25-d35d-4653-93b9-409e88a37d4f)

## Steps to QA

## Added to documentation?
- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

## [Optional] Post-deployment tasks
[Specify any post-deployment tasks that need to be performed]

## [Optional] What gif best describes this PR or how it makes you feel? 
[Embed gif or describe the feeling in plain text]

2024-05-18 12:07 UTC, cleancodecraft requested changes
@MestiriBaha 
very interesting, where do you see this ? 

because what I see it this - 

![image](https://github.com/AnguHashBlog/angular-primeng/assets/132580309/b11f8d5b-a1e3-4ef4-ab69-ac94070d4fc2)

2024-05-18 12:16 UTC, MestiriBaha commented
Hello , please try to check the blog post where the author is "monacodeLisa" and  where there is not co-authors , there where I found the problem !

2024-05-18 18:35 UTC, monacodelisa commented
@MestiriBaha ok I saw it -

![image](https://github.com/AnguHashBlog/angular-primeng/assets/64324417/b2f704c4-7b0e-432f-9a91-b15364bd6580)

this vas a very good catch thank you for finding this :) 

So what we want to do in this case - is to explore the GraphQL query, 
since the values are retrieved from the [Hashnode's API](https://gql.hashnode.com) and ->
if one time the response is `monacodelisa` and another time it's `{{ MonaCodeLisa }}` there is some inconsistency.

I tested the queries, first: 

![Screenshot_19](https://github.com/AnguHashBlog/angular-primeng/assets/64324417/c7c2ddd8-939c-4ae5-9114-26e81442b061)

and then -

![Screenshot_20](https://github.com/AnguHashBlog/angular-primeng/assets/64324417/e6e2135d-3be6-4b99-b14f-b172f9262fb3)

after that I verified the query that we have in the file `graphql.operations.ts` and can you guess what showed up 

![Screenshot_21](https://github.com/AnguHashBlog/angular-primeng/assets/64324417/ee063bb0-b6c2-4a40-aca7-0fb91b985a90)

The problem is that in our query on line 139, we have: 

```
				author {
					name
					profilePicture
				}
```

when it needs to be:

```
				author {
					username
					profilePicture
				}
```

it repeats also on line 175 - just below `author` it still needs to be `username`

I do appreciate your work creating the pipe, but for this case we need to fix the root cause. 

I am going to close this PR and I will write another issue soon - where I will mention everything from this conversation.

I will have to do this across all the app versions. If you would like - once the issue is created in this repo - I can assign it to you, after all you found it :)

2024-05-18 18:35 UTC, closed without merging

2024-05-18 18:52 UTC, monacodelisa commented
@MestiriBaha here is the new issue - #74 if you would like to take it just leave a comment bellow the issue.
It has higher priority, so this one should be done before #61

2024-05-19 00:04 UTC, MestiriBaha commented
@monacodelisa , Thank you so much for your feedback  ! I doubted in first place that the root problem can be from the Queries however because of my "little" knowledge of GraphQL syntax , I didn't dig deeper into it , but now , I want to explore the GraphQL query syntax and fix the root of the problem , I would like to take on this issue so assign me on it please !

2024-05-19 06:48 UTC, monacodelisa commented
@MestiriBaha ok so what you need to do is head over to the issue [https://github.com/AnguHashBlog/angular-primeng/issues/74](https://github.com/AnguHashBlog/angular-primeng/issues/74)

and leave a comment there, because if your comment is not there, your name does not appear and I cannot assign you

![image](https://github.com/AnguHashBlog/angular-primeng/assets/64324417/25ffb138-e4d8-41ab-a337-82c31dac6eb9)